### ISSUE TITLE
New package "winston-raven-sentry"

### ISSUE THREAD

**Issue by niftylettuce** [dcharbonnier/raven-winston-ya#1]
For anyone that needs a newer maintained version: https://github.com/niftylettuce/winston-raven-sentry

**Comment by dcharbonnier** [comment]
lol, if you have an issue with this one, post it and it will be maintained ;-)

**Comment by niftylettuce** [comment]
4 months later

**Comment by dcharbonnier** [comment]
https://github.com/aandrewww/winston-sentry-raven-transport
